# Training configuration for Model A

seed: 42

data:
  dataset: 'dataset_A'  # Options: 'dataset_A', 'dataset_B'
  batch_size: 1
  num_workers: 16
  lead_time_hours: 24 # Initially 24; how far away is the next forecast
  multistep: 7 # how many forecasting iterations during testing

output:
  model_save_path: 'models/model_a/saved_models/'
  # model_save_path: '/mnt/output/models/model_a/saved_models/'

wandb:
  project: 'da_pangu'
